nomeCompleto = input('Digite seu nome completo:\n')
nomeCortado = ''.join(nomeCompleto.split())
print('\033[1;7;30mNome em maiusculas:\033[m', nomeCompleto.upper())
print('\033[1;31mNome em minusculas:\033[m', nomeCompleto.lower())
print('\033[1;7;32mQuantidade de letras (sem espaços):\033[m', len(nomeCortado))
print('\033[1;33mQuantidade de letras do primeiro nome:\033[m',len(nomeCompleto.split()[0]))